#!/bin/bash
stamp=`date +%F`
name=${2:-${stamp}}
remote=${3:-origin}
branch=${4:-master}
dir=${1:?"Usage: $0 dir [name=${name}] [remote=${remote}] [branch=${branch}] [options]"}
mailto='avdi.grimm+admin@gmail.com'
echo "Date: `date --rfc-2822 --utc`"
echo "Backing up ${dir}"
echo "Backup name: ${name}"
echo "Remote: ${remote}"
echo "Branch: ${branch}"
cd ${dir} 2>&1 && \
    git add -A 2>&1 && \
    git commit -m "${name}" 2>&1 && \
    git push ${remote} ${branch}




